### ISSUE TITLE
Missing service on reference-pipeline-structure.md

### ISSUE THREAD

**Issue by huribeir** [awsdocs/aws-codepipeline-user-guide#22]
This was supposed to be a pull request for [reference-pipeline-structure.md](https://github.com/awsdocs/aws-codepipeline-user-guide/blob/master/doc_source/reference-pipeline-structure.md), but the code for the table displayed on the documentation is not present on this file.

Essentially, the table in **Valid Action Types and Providers in CodePipeline** lists CodeDeploy and Amazon ECS under the *Deploy* section, but it does not have a separate entry for CodeDeployToECS/Amazon ECS (Blue/Green), like it does on the table **Action Configuration Properties for Provider Types** further down the page.

This could lead to confusion and pipeline misconfigurations, where one could assume it should use one of the two entries for configuring ECS Blue/Green deployments. My suggestion is that a new line is added to that table to explicitly list what is seen on the AWS Console and other parts of the configuration, making distinction of this third option "Amazon ECS (Blue/Green)".

Thanks!

**Comment by darlaker** [comment]
Hello, Thank you so much for this suggestion, and for adding this as an issue here (sorry PRs are not available in the markdown for this table). I agree - the CodeDeploy to ECS Blue/Green action is a separate and distinct action that should have been added to this table. Since it was missing from this table, that could definitely cause confusion. This has been corrected in the CodePipeline User Guide here: https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#actions-valid-providers. Thank you so much for your feedback on the docs!

**Comment by darlaker** [comment]
Closing issue after correcting in the document.
